GET http://localhost:3000/contacts

###
GET http://localhost:3000/contacts/626daf33250f564918196a24

###

GET https://cse341course.herokuapp.com/contacts

###
GET https://cse341course.herokuapp.com/626daf33250f564918196a24